# Generated by Django 5.1 on 2024-10-15 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CausaAtencion',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causaAtencion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Causa Atencion',
                'verbose_name_plural': 'Causas de Atención',
                'db_table': 'causaAtencion',
            },
        ),
        migrations.CreateModel(
            name='ComunidadEtnia',
            fields=[
                ('codComunidadEtnia', models.IntegerField(primary_key=True, serialize=False)),
                ('desComunidad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Comunidad Etnia',
                'verbose_name_plural': 'Comunidades Etnicas',
                'db_table': 'comunidadEtnia',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoMunicipio',
            fields=[
                ('codDepartamentoMunicipio', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('DepartamentoMunicipio', models.CharField(max_length=100)),
                ('padre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento Municipio',
                'verbose_name_plural': 'Departamentos Municipios',
                'db_table': 'departamentoMunicipio',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('codDiagnostico', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=200)),
                ('padre', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
                'db_table': 'diagnostico',
            },
        ),
        migrations.CreateModel(
            name='Discapacidades',
            fields=[
                ('codDiscapacidad', models.IntegerField(primary_key=True, serialize=False)),
                ('calDiscapacidad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Discapacidad',
                'verbose_name_plural': 'Discapacidades',
                'db_table': 'discapacidades',
            },
        ),
        migrations.CreateModel(
            name='EntidadSalud',
            fields=[
                ('codEntidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nomEntidad', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Entidad Salud',
                'verbose_name_plural': 'Entidades de Salud',
                'db_table': 'entidadSalud',
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('codOcupacion', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('desOcupacion', models.CharField(max_length=200)),
                ('padre', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Ocupacion',
                'verbose_name_plural': 'Ocupaciones',
                'db_table': 'ocupacion',
            },
        ),
        migrations.CreateModel(
            name='OpocisionDonacion',
            fields=[
                ('idDonacion', models.IntegerField(primary_key=True, serialize=False)),
                ('manifestacionOpo', models.CharField(choices=[('01', 'Si'), ('02', 'No')], max_length=2)),
                ('fechaDonacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Oposición Donación',
                'verbose_name_plural': 'Oposicion Donaciones',
                'db_table': 'opocisionDonacion',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False)),
                ('nomPais', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='PrestadoresSalud',
            fields=[
                ('codPrestadorSalud', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('prestadoresSalud', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Prestador Salud',
                'verbose_name_plural': 'Prestadores de Salud',
                'db_table': 'prestadoresSalud',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentos',
            fields=[
                ('idTipoDocumento', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcionDocumento', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipoDocumento',
            },
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('idTriage', models.AutoField(primary_key=True, serialize=False)),
                ('fechaTriage', models.DateField()),
                ('horaTriage', models.TimeField()),
                ('ClasificacionTriage', models.CharField(choices=[('01', 'TRIAGE I'), ('02', 'TRIAGE II'), ('03', 'TRIAGE III'), ('04', 'TRIAGE IV'), ('05', 'TRIAGE V')], max_length=2, verbose_name='Clasificacion de triage')),
            ],
            options={
                'verbose_name': 'Triage',
                'verbose_name_plural': 'Triages',
                'db_table': 'triage',
            },
        ),
        migrations.CreateModel(
            name='ViaIngresoServicio',
            fields=[
                ('idViaIngresoServicio', models.IntegerField(primary_key=True, serialize=False)),
                ('desIngresoServicio', models.CharField(max_length=99)),
            ],
            options={
                'verbose_name': 'Via Ingreso Servicio',
                'verbose_name_plural': 'Vias Ingresos de Servicio',
                'db_table': 'via_ingreso_servicio',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.IntegerField()),
                ('primer_nombre', models.CharField(max_length=60)),
                ('segundo_nombre', models.CharField(max_length=60, null=True)),
                ('primer_apellido', models.CharField(max_length=60)),
                ('segundo_apellido', models.CharField(max_length=60, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('hora_nacimiento', models.TimeField()),
                ('sexo_biologico', models.CharField(choices=[('01', 'Hombre'), ('02', 'Mujer'), ('03', 'Indeterminado/Intersexsual')], max_length=2)),
                ('ident_genero', models.CharField(choices=[('01', 'Masculino'), ('02', 'Feminino'), ('03', 'Transgenero'), ('04', 'Neutro'), ('05', 'No lo declara')], max_length=2)),
                ('etnia', models.CharField(choices=[('01', 'Indigena'), ('02', 'ROM (Gitanos)'), ('03', 'Raizal (San Andrés y Providencia)'), ('04', 'Palenquero de San Basillo de Palenque'), ('05', 'Negro(a)'), ('06', 'Afrocolombiano(a)'), ('99', 'Ninguna de las anteriores')], max_length=2)),
                ('zona_residencia', models.CharField(choices=[('01', 'Urbana'), ('02', 'Rural')], max_length=2)),
                ('comunidad_etnia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.comunidadetnia')),
                ('departamento_municipio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.departamentomunicipio')),
                ('donacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.opocisiondonacion')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.entidadsalud')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nacionalidad_usuario', to='clinica.pais')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.ocupacion')),
                ('pais_residencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pais_usuario', to='clinica.pais')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.tipodocumentos')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioDiscapacidad',
            fields=[
                ('idUsuarioDiscapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('discapacidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.discapacidades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Discapacidad',
                'verbose_name_plural': 'Usuarios Discapacidad',
                'db_table': 'usuario_discapacidad',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPais',
            fields=[
                ('idUsuarioPais', models.AutoField(primary_key=True, serialize=False)),
                ('idPais', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.pais')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Pais',
                'verbose_name_plural': 'Usuarios Pais',
                'db_table': 'usuario_pais',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicioSalud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateField()),
                ('hora_atencion', models.TimeField()),
                ('modalidad_servicio', models.CharField(choices=[('01', 'Intramural'), ('02', 'Extramural unidad móvil'), ('03', 'Extramural domiciliaria'), ('04', 'Extramural jornada de salud'), ('05', 'Extramural (atención pre hospitalaria o transporte asistencial)'), ('06', 'Telemedicina interactiva'), ('07', 'Telemedicina no interactiva'), ('08', 'Telemedicina - Telexperticia'), ('09', 'Telemedicina - Telemonitoreo')], max_length=2)),
                ('grupo_servicio', models.CharField(choices=[('01', 'Consulta Externa'), ('02', 'Apoyo diagnóstico y complementación terapéutica'), ('03', 'Internación'), ('04', 'Quirúrgico'), ('05', 'Atención Inmediata')], max_length=2)),
                ('entorno_atencion', models.CharField(choices=[('01', 'Hogar'), ('02', 'Comunitario'), ('03', 'Escolar'), ('04', 'Laboral'), ('05', 'Institucional')], max_length=2)),
                ('t_diagnostico', models.CharField(choices=[('01', 'Impresión diagnóstica'), ('02', 'Confirmado nuevo'), ('03', 'Confirmado repetido')], max_length=2)),
                ('causa_atencion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.causaatencion')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.diagnostico')),
                ('prestador_salud', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.prestadoressalud')),
                ('triage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.triage')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.usuario')),
                ('via_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.viaingresoservicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios de Salud',
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='VoluntaAnticipada',
            fields=[
                ('idVoluntad', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('docVoluntad', models.CharField(choices=[('01', 'Si'), ('02', 'No')], max_length=200)),
                ('fecha', models.DateField(blank=True, max_length=10, null=True)),
                ('codPrestadorSalud', models.ForeignKey(max_length=12, null=True, on_delete=django.db.models.deletion.RESTRICT, to='clinica.prestadoressalud')),
            ],
            options={
                'verbose_name': 'Voluntad Anticipada',
                'verbose_name_plural': 'Voluntades Anticipadas',
                'db_table': 'voluntaAnticipada',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='voluntad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.voluntaanticipada'),
        ),
    ]
