# Generated by Django 5.1 on 2024-10-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_usuario_options_usuario_discapacidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nacionalidad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.ManyToManyField(blank=True, related_name='nacionalidad_usuario', to='clinica.pais'),
        ),
    ]
